name: test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

  schedule:
    # 6:00 A.M UTC  == 9:00 AM EAT
    - cron: "0 6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Test
        run: curl https://raw.githubusercontent.com/SenZmaKi/YTMusicBot/master/cloud/install.sh | bash -s -- --test